DROP TABLE IF EXISTS [dbo].[Notes];
DROP TABLE IF EXISTS [dbo].[Notebooks];
DROP TABLE IF EXISTS [dbo].[Profiles];
DROP TABLE IF EXISTS [dbo].[Users];

CREATE TABLE Users
(
	userID NVARCHAR(200) PRIMARY KEY NOT NULL,
	dateCreated DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateModified DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Profiles
(
	profileID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),
	fk_userID NVARCHAR(200) NOT NULL UNIQUE FOREIGN KEY REFERENCES Users(userID),
	name NVARCHAR(100),
	email NVARCHAR(64),
	picture NVARCHAR(400),
	nickname NVARCHAR(100)
);

CREATE TABLE Notebooks
(
	notebookID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),
	fk_userID NVARCHAR(200) NOT NULL FOREIGN KEY REFERENCES Users(userID),
	name NVARCHAR(200),
	noteCount INT DEFAULT 0,
	dateCreated DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateModified DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Notes
(
	noteID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),
	fk_notebookID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Notebooks (notebookID) NOT NULL,
	title NVARCHAR(300),
	type INT NOT NULL,
	content NVARCHAR(MAX) NOT NULL,
	dateCreated DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateModified DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
);